services:
  db:
    image: pgvector/pgvector:pg15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - llm_chat_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm_chat_image
    container_name: llm_chat_migrations
    command: ["alembic", "upgrade", "head"]
    env_file: .env
    networks:
      - llm_chat_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=${POSTGRES_URL}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm_chat_image
    container_name: llm_chat_app
    command: >
      sh -c "
      echo Fetching the embedding model and populating the vector DataBase
      && echo It might take a couple of minutes...
      && python populate_db.py
      && echo Service is ready to use!
      && streamlit run main.py --server.port=8501 --server.address=0.0.0.0
      "
    ports:
      - "8501:8501"
    env_file: .env
    networks:
      - llm_chat_network
    depends_on:
      - db
      - migrations
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - POSTGRES_URL=${POSTGRES_URL}

volumes:
  postgres_data:

networks:
  llm_chat_network: